name: cd

on:
#   workflow_run:
#     workflows: ["main-ci"]
#     types: [completed]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

concurrency:
  group: cd-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout triggering commit
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.workflow_run.repository.full_name }}
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.x

      - name: Terraform init
        working-directory: terraform/ecs
        run: terraform init -input=false -no-color

      - name: Terraform apply
        working-directory: terraform/ecs
        run: terraform apply -auto-approve -input=false -no-color
