name: cd

on:
  workflow_run:
    workflows: ["main-ci"]
    types: [completed]

permissions:
  id-token: write
  contents: read

concurrency:
  group: cd-${{ github.event.workflow_run.head_branch }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest branch state
        uses: actions/checkout@v4
        with:
          ref: refs/heads/${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.x

      - name: Terraform fmt (check)
        run: terraform fmt -recursive -check -diff

      - name: Terraform init
        working-directory: terraform/ecs
        run: terraform init -input=false -no-color

      - name: Terraform validate
        run: terraform validate -no-color

      - name: Terraform apply
        working-directory: terraform/ecs
        run: terraform apply -auto-approve -input=false -no-color
