name: terraform-ci

on:
  push:
    branches:
      - "**"
    paths:
      - "terraform/**"
  pull_request:
    paths:
      - "terraform/**"
  workflow_dispatch:

jobs:
  tf-check:
    name: "Terraform check (${{ matrix.stack }})"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        stack:
          - terraform/bootstrap
          - terraform/ecr
          - terraform/ecs

    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.stack }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.x

      - name: Cache Terraform providers
        uses: actions/cache@v4
        with:
          path: |
            ~/.terraform.d/plugin-cache
            ${{ matrix.stack }}/.terraform
          key: tf-${{ matrix.stack }}-${{ hashFiles(format('{0}/.terraform.lock.hcl', matrix.stack)) }}
          restore-keys: |
            tf-${{ matrix.stack }}-

      - name: Terraform fmt (check)
        run: terraform fmt -recursive -check -diff

      - name: Terraform init (no backend)
        run: terraform init -backend=false -input=false -no-color

      - name: Terraform validate
        run: terraform validate -no-color
